name: wheretosleepinnju
description: A new Flutter project.

version: 1.6.0+20

environment:
  sdk: ">=2.1.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^0.5.6+3
  flutter_swiper: ^1.1.6
  image_picker: ^0.6.5
  package_info: ^0.4.0+16
  path_provider: ^1.6.7
  barcode_scan: ^2.0.2
  url_launcher: ^5.4.2
  scoped_model: ^1.0.1
  fluttertoast: ^4.0.1
  qr_flutter: ^3.2.0
  sqflite: ^1.3.0
  html:
    git:
      url: git://github.com/chen-zeyu/html.git
      ref: patch-pola
  dio: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - res/icon.png
flutter_intl:
  enabled: true
