name: wheretosleepinnju
description: wheretosleepinnju

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.4+26

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.0.7
  flutter_swiper_null_safety: ^1.0.2
  image_picker: ^0.8.4
  package_info: ^2.0.2
  webview_flutter: ^2.0.13
  path_provider: ^2.0.3
#  barcode_scan: ^2.0.2
  url_launcher: ^6.0.10
  scoped_model: ^2.0.0-nullsafety.0
  fluttertoast: ^8.0.1
  qr_flutter: ^4.0.0
  sqflite: ^2.0.0+4
  html: ^0.15.0
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - res/icon.png

flutter_intl:
  enabled: true

analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true
