name: wheretosleepinnju
description: wheretosleepinnju

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+22

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^0.5.12+2
  flutter_swiper: ^1.1.6
  image_picker: ^0.6.5
  package_info: ^0.4.0+16
  webview_flutter: ^1.0.3
  path_provider: ^1.6.7
  barcode_scan: ^2.0.2
  url_launcher: ^5.4.2
  scoped_model: ^1.0.1
  fluttertoast: ^4.0.1
  qr_flutter: ^3.2.0
  sqflite: ^1.3.0
  html:
    git:
      url: git://github.com/chen-zeyu/html.git
      ref: patch-pola
  dio: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - res/icon.png

flutter_intl:
  enabled: true

analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true
